
import React from "react";
import Profilecard from "@/components/Profilecard";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Babyoyz || About",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <main className="">
        <div className="flex justify-center mt-10">
          <Profilecard />
        </div>
      </main>
    </>
  );
}

export default page;
