import Image from "next/image";
import type { Metadata } from "next";
import dynamic from "next/dynamic";

const MultipleCarousel = dynamic(
  () => import("@/components/MultipleCarousel"),
  {
    loading: () => (
      <div className=" w-full h-screen  overflow-hiddenopacity-75 flex flex-col items-center justify-center">
        <div className="loader ease-linear rounded-full border-4 border-t-4 border-gray-200 h-12 w-12 mb-4"></div>
      </div>
    ),
  }
);

export const metadata: Metadata = {
  title: "Babyoyz || Main",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="">
      <div className="Corasel">
        <MultipleCarousel label="My Motocyle" Images={[]} />
      </div>
    </main>
  );
}
