import Image from 'next/image'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Babyoyz || Main",
  description: "Generated by create next app",
};

export default function Home() {
return (
    <main className="">
        <div className='Corasel'>
        <div className="flex h-screen justify-center items-center">
            <div className="flex flex-col">
              <div className="flex-grow"></div>
              <div className="flex-shrink text-center">
                <p className="text-2xl">Coming Soon ...</p>
              </div>
              <div className="flex-grow"></div>
            </div>
          </div>

        </div>
    </main>
  )
}
